id: I38BB904C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T13:16:27+00:00'
last_modified: '2022-06-08T10:47:25.549251+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27269
  title: འབྱུང་བཞིའི་ཆོ་ག་དག་བྱེད་བདུད་རྩིའི་ཆུ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FB6A:
      image_group_id: I1CZ939
      title: ''
      total_pages: 20
      order: 1
      base_file: FB6A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
