id: P009406
initial_creation_type: ocr
source_metadata:
  id: bdr:W27269
  title: འབྱུང་བཞིའི་ཆོ་ག་དག་བྱེད་བདུད་རྩིའི་ཆུ
  author: ''
  volumes:
    65a4278992104cb7b3f7b4526165a6fd:
      image_group_id: I1CZ939
      title: ''
      volume_number: 1
      total_pages: 20
      base_file: v001.txt
